### ISSUE TITLE
Trying to compile from manjaro hc4 image not working

### ISSUE THREAD

**Issue by ptr1337** [jgmdev/alarm-image-generator#2]
Just installed the new HC4 minimal image from manjaro, but i dont find these dependecies since theyre using their own package in the repo. 

I think i have to add the offical repos to the pacman list, maybe it will work then ?

`[ptr@odroidhc4 alarm-image-generator]$ sudo ./build.sh build -e minimal c4
Please install 'mkfs.vfat arch-chroot' to use this script.`

**Comment by jgmdev** [comment]
mkfs.vfat is part of the dosfstools package.

**Comment by ptr1337** [comment]
Got it ty. Sorry for the issue. 

yay -S arch-install-scripts dosfstools resolved. Building now :)

**Comment by ptr1337** [comment]
Build was successful, Does it support petitboot ? 
Mostly using my SBCs only headless.

**Comment by jgmdev** [comment]
should work with petitboot and latest uboot package ships a boot.ini that has some option to force resolutions for problematic displays:

https://github.com/archdroid-org/pkgbuilds/blob/master/uboot-odroid-n2plus/boot.mainline.ini#L16-L41

**Comment by ptr1337** [comment]
Yeah, dont using a Display. If i got int sucessfully installed later, i can provide you the image for your site.
