### ISSUE TITLE
Adding cross compiling

### ISSUE THREAD

**Issue by ptr1337** [jgmdev/alarm-image-generator#3]
Since it is possbile on arch to install cross compiler it should work to build a image with the cross compilers.

**Comment by ptr1337** [comment]
If you want to add this feature, i can create a docker container for cross compiling from any machine.

**Comment by jgmdev** [comment]
I haven't played with this idea but maybe calling makepkg with a custom makepkg.conf file that is configured to use a different compiler would do the trick and installing binfmt-qemu-static-all-arch for the aarch64 chroot that is needed to configure the image.

**Comment by ptr1337** [comment]
Or just use a docker container which got arm64 architectur and binfmt-static-all-arch or there is a docker container for multiarch binfmt. 

If i got some time, ill try to create a build in docker.
